[package]
name = "harpooner"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = "1"
rocket = "0.4.10"
mongodb = "2.5.0"
rand = "0.8.5"
reqwest = "0.11.17"
serde_json = "1.0.96"
serenity = "0.11"
chrono = "0.4.24"